### ISSUE TITLE
Fails on FreeBSD

### ISSUE THREAD

**Issue by probonopd** [ondratu/formiko#26]
When following the instructions, it fails on FreeBSD 12.1:

```
user@FreeBSD$ sudo pkg install py37-pygments py37-docutils py37-pip
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: gstreamer1-plugins-lame has a missing dependency: lame
pkg: k3b has a missing dependency: lame
The following 2 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
        py37-pip: 19.1.1 -> 20.2.3
        py37-pygments: 2.5.2 -> 2.7.1

Number of packages to be upgraded: 2

The process will require 2 MiB more space.
3 MiB to be downloaded.

Proceed with this action? [y/N]: y
[1/2] Fetching py37-pygments-2.7.1.txz: 100%    1 MiB   1.3MB/s    00:01    
[2/2] Fetching py37-pip-20.2.3.txz: 100%    2 MiB   2.1MB/s    00:01    
Checking integrity... done (0 conflicting)
[1/2] Upgrading py37-pygments from 2.5.2 to 2.7.1...
[1/2] Extracting py37-pygments-2.7.1: 100%
[2/2] Upgrading py37-pip from 19.1.1 to 20.2.3...
[2/2] Extracting py37-pip-20.2.3: 100%

user@FreeBSD$ sudo pip-3.7 install formiko
Collecting formiko
  Downloading formiko-1.4.3-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 2.0 MB/s 
Requirement already satisfied: docutils>=0.12 in /usr/local/lib/python3.7/site-packages (from formiko) (0.15.2)
Installing collected packages: formiko
Successfully installed formiko-1.4.3

user@FreeBSD$ formiko
Traceback (most recent call last):
  File "/usr/local/bin/formiko", line 5, in <module>
    from formiko.main import main
  File "/usr/local/lib/python3.7/site-packages/formiko/main.py", line 11, in <module>
    from formiko.application import Application
  File "/usr/local/lib/python3.7/site-packages/formiko/application.py", line 10, in <module>
    from formiko.window import AppWindow
  File "/usr/local/lib/python3.7/site-packages/formiko/window.py", line 14, in <module>
    from formiko.sourceview import SourceView, View as GtkSourceView
  File "/usr/local/lib/python3.7/site-packages/formiko/sourceview.py", line 2, in <module>
    require_version('GtkSource', '3.0')     # noqa
  File "/usr/local/lib/python3.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available

```

**Comment by ondratu** [comment]
Hi, problem which you have is that you don't have gnome3 installed yet. So follow next install section:
``` sh
pkg install py37-gobject3 py37-docutils py37-pygments py37-pip \
    gtksourceview3 webkit2-gtk3 gtkspell3 gobject-introspection \
    librsvg2 adwaita-icon-theme
```

But ok, i will change install instruction to be clear.

**Comment by probonopd** [comment]
Thanks for the explanation @ondratu.

From the description I thought that Gtk was enough:

> Formiko is reStructuredText and MarkDown editor and live previewer. It is written in Python with Gtk3, GtkSourceView and Webkit2. 

I am not using Gnome and I don't want to install it.
