### ISSUE TITLE
Nothing rendered in the preview pane

### ISSUE THREAD

**Issue by jinnko** [ondratu/formiko#3]
Using formiko v1.3.0 as packaged on Ubuntu 18.04, I get nothing rendered in the preview pane.

Have followed the instructions in the README.md of this repo and that hasn't helped.

Running formiko-vim from the CLI there are a couple of errors displayed.

```
E247: No registered server named "62B1E33A-1BC2-4E1C-8B60-55D079C9F3DB": Send expression failed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/formiko/window.py", line 409, in refresh_from_vim
    row, col = self.editor.get_vim_pos()
  File "/usr/lib/python3/dist-packages/formiko/vim.py", line 75, in get_vim_pos
    buff, row, col, off = pos.split('\n')
ValueError: not enough values to unpack (expected 4, got 1)
```
FWIW - I'm using neovim, but I doubt this is an issue as the editor pane is working just fine with the embedded vim instance.

**Comment by ondratu** [comment]
Hi, could you tell me, which packages of vim and/or neovim you have installed, and how is configure your vim and gvim alternative?
```bash
~$ update-alternatives --display vim
~$ update-alternatives --display gvim
```

The problem is with vim backend, which is start on background as server, but I don't know why.

**Comment by fdobad** [comment]
Hi, I really like formiko-vim!

Should I hijack this thread because the title is accurate? If not I can repeat the post into another issue, here it goes:

I recently started using nvidia drivers, now can't get any preview.
Starting from the cli yields
```
~$ formiko-vim                                                                                                                        
Cannot create EGL sharing context: error binding OpenGL API (EGL_BAD_PARAMETER)                                                                   
                                    
(WebKitWebProcess:128070): Gdk-ERROR **: 09:20:04.269: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was '179'.
  (Details: serial 188 error_code 179 request_code 154 (unknown) minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
And I'm using debian bullseye (clean install a few days ago after the drivers mess, except that they are `nvidia-legacy-340xx-drivers` from buster-backports).

I hope this is not a painful bug
```
~$ update-alternatives --display gvim
gvim - auto mode
  link best version is /usr/bin/vim.gtk3
  link currently points to /usr/bin/vim.gtk3
  link gvim is /usr/bin/gvim
/usr/bin/vim.gtk3 - priority 50

~$ update-alternatives --display vim
vim - auto mode
  link best version is /usr/bin/vim.gtk3
  link currently points to /usr/bin/vim.gtk3
  link vim is /usr/bin/vim
/usr/bin/vim.gtk3 - priority 50

```

**Comment by ondratu** [comment]
Hi, thanks, but this is different error, and it looks to OpenGL problem with your driver. Can you sand me your source code? Did you try generate same specific HTML? Or including specific image, video or something like that?

I can handle this error, if i can replicate it.

**Comment by fdobad** [comment]
Hi!

I tried many files from `https://github.com/mattcone/markdown-guide/tree/master/_basic-syntax` and didn't get any render, even changing all settings (different from common mark parser and docutils html4 writer. 

I did got good renders before installing the nvidia drivers though... So I tried removing and reinstalling (`# apt -f install formiko`) without results. After fiddling around a bit more, got the same initial error 179.

I'm using debian 11 on an old MacBook Pro 5,2 (late 2010 so without nvidia drivers gnome looks laggy af).

`dmesg` has some nvidia warnings but no errors

Maybe `journaltcl` has more insights:
```
Apr 20 16:02:17 macbp52 kernel: traps: eadedCompositor[13345] trap int3 ip:7f799a47cabb sp:7f7942c32e70 error:0 in libglib-2.0.so.0.6600.8[7f799a>
Apr 20 16:02:06 macbp52 systemd[683]: app-gnome-formiko\x2dvim-12303.scope: Consumed 35.898s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit UNIT completed and consumed the indicated resources.
Apr 20 16:02:06 macbp52 systemd[683]: app-gnome-formiko\x2dvim-12303.scope: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit UNIT has successfully entered the 'dead' state.
Apr 20 16:01:59 macbp52 wpa_supplicant[521]: wlan0: WPA: Group rekeying completed with 0c:80:63:27:32:46 [GTK=CCMP]
Apr 20 16:01:48 macbp52 kernel: traps: eadedCompositor[13146] trap int3 ip:7f7956723abb sp:7f78fee32e70 error:0 in libglib-2.0.so.0.6600.8[7f7956>
Apr 20 16:01:48 macbp52 WebKitWebProces[13125]: The program 'WebKitWebProcess' received an X Window System error.
                                                This probably reflects a bug in the program.
                                                The error was '179'.
                                                  (Details: serial 188 error_code 179 request_code 154 (unknown) minor_code 21)
                                                  (Note to programmers: normally, X errors are reported asynchronously;
                                                   that is, you will receive the error a while after causing it.
                                                   To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                   variable to change this behavior. You can then get a meaningful
                                                   backtrace from your debugger if you break on the gdk_x_error() function.)
Apr 20 16:01:48 macbp52 formiko-vim.desktop[13125]: Cannot create EGL sharing context: error binding OpenGL API (EGL_BAD_PARAMETER)
```

Thanks!
