### ISSUE TITLE
dash space link (- <https://somelink.com> crashes

### ISSUE THREAD

**Issue by twmoore3rd** [ondratu/formiko#31]
Markdown consisting of a dash, a space, and a link

- <https://google.com>

crashes the preview.

However (space deleted between dash and less then

-<https://google.com>

and

- <https://google.com>
-<https://google.com>

does not crash though the latter puts both links on the same preview line.

**Comment by ondratu** [comment]
Hi, cold you tell me more information about your formiko version and libraries ?

last git version with these versions works fine.
```
m2r                 0.2.1
docutils             0.16
Pygments            2.7.1
```

**Comment by twmoore3rd** [comment]
On Linux Mint, I used Synaptic Package Manager to install `m2r` which in turn installed `docutils` and `Pygments` as all three packages showed as not being in the (Python?) environment.

After installation of m2r and the other two packages, the preview test case worked.

Suggestions: 

- While Formiko does not crash to the command line if m2r (and docutils and Pygments) is not installed (have to love good exception handling), the ungraceful preview almost crash may suggest that m2r (and docutils and Pygments) should be a requirement and merely a recommended.
- Upon installation, is it possible for Formiko to warn which required and recommended libraries are not present?

Am closing this issue as once the recommended libraries are installed, preview appears to work.

Thank you for your work on this project.

**Comment by ondratu** [comment]
Thanks,

* Pygments are only for code syntax highlighting in exported document, so it has't effect to this issue.
* When you don't have m2r installed, this option (Markdown to ResturcturedText option is disabled), and document is parsed as RsT, which is not perfect, and I try to solve this situation.
* Docutils is main require library, without it, Formiko must not start, but you have right, that it can show some better error message.

I'm thinking about requirements, and i will do some cleanup in them, and if some of then does not exist, formiko will tell it in some right way (dialog, message, notification, I'm not sure now).

**Comment by Elliria** [comment]
My setup:
* Formiko 1.4.3
* m2r 0.3.1
* docutils 0.20.1
* Kubuntu 24.04 LTS
* Xorg

I realize that this issue is closed, but I'm currently experiencing it.

### Example 1:
```markdown
# Hello world

* [Google](https://www.google.com)
```
Formiko output:
```
Exception Error!

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 374, in render_output
    html = publish_string(**kwargs).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 460, in publish_string
    output, publisher = publish_programmatically(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 722, in publish_programmatically
    output = publisher.publish(enable_exit_status=enable_exit_status)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 236, in publish
    self.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 216, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/transforms/__init__.py", line 182, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 53, in apply
    self.traverse(self.document)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 313, in traverse
    self.traverse(child)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 303, in traverse
    newnode = self.find_replace(c)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 283, in find_replace
    newnode = self.auto_toc_tree(node)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 182, in auto_toc_tree
    return self.state_machine.run_directive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/states.py", line 93, in run_directive
    direc = direc(name=name,
            ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

### Example 2:
```markdown
# Hello world

- [Google](https://www.google.com)
```
Formiko output:
```
Exception Error!

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 374, in render_output
    html = publish_string(**kwargs).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 460, in publish_string
    output, publisher = publish_programmatically(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 722, in publish_programmatically
    output = publisher.publish(enable_exit_status=enable_exit_status)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 236, in publish
    self.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 216, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/transforms/__init__.py", line 182, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 53, in apply
    self.traverse(self.document)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 313, in traverse
    self.traverse(child)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 303, in traverse
    newnode = self.find_replace(c)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 283, in find_replace
    newnode = self.auto_toc_tree(node)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 182, in auto_toc_tree
    return self.state_machine.run_directive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/states.py", line 93, in run_directive
    direc = direc(name=name,
            ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

### Example 3:
```markdown
# Hello world

- foo [Google](https://www.google.com)
```
Formiko output:
- foo [Google](https://www.google.com)

### Example 4:
```markdown
# Hello world

* foo [Google](https://www.google.com)
```
Formiko output:
* foo [Google](https://www.google.com)

### Example 5:
```markdown
# Hello world

* [Google](https://www.google.com) foo
```

Formiko output:
* [Google](https://www.google.com) foo


### Example 6:
```markdown
# Hello world

- [Google](https://www.google.com) foo
```

Formiko output:
- [Google](https://www.google.com) foo

### Example 7:
```markdown
# Hello world

- [Google](https://www.google.com)
- foo
```
Formiko output:
- [Google](https://www.google.com)
- foo

### Example 8:
```markdown
# Hello world

* [Google](https://www.google.com)
* foo
```
Formiko output:
* [Google](https://www.google.com)
* foo

### Example 9:
```markdown
# Hello world

- foo
- [Google](https://www.google.com)
```
Formiko output:
- foo
- [Google](https://www.google.com)

### Example 10:
```markdown
# Hello world

* foo
* [Google](https://www.google.com)
```
Formiko output:
* foo
* [Google](https://www.google.com)

### Example 11:
```markdown
# Hello world

foo
- [Google](https://www.google.com)
```
Formiko output:
```
Exception Error!

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 374, in render_output
    html = publish_string(**kwargs).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 460, in publish_string
    output, publisher = publish_programmatically(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 722, in publish_programmatically
    output = publisher.publish(enable_exit_status=enable_exit_status)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 236, in publish
    self.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 216, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/transforms/__init__.py", line 182, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 53, in apply
    self.traverse(self.document)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 313, in traverse
    self.traverse(child)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 303, in traverse
    newnode = self.find_replace(c)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 283, in find_replace
    newnode = self.auto_toc_tree(node)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 182, in auto_toc_tree
    return self.state_machine.run_directive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/states.py", line 93, in run_directive
    direc = direc(name=name,
            ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

### Example 12:
```markdown
# Hello world

foo
* [Google](https://www.google.com)
```
Formiko output:
```
Exception Error!

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 374, in render_output
    html = publish_string(**kwargs).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 460, in publish_string
    output, publisher = publish_programmatically(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 722, in publish_programmatically
    output = publisher.publish(enable_exit_status=enable_exit_status)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 236, in publish
    self.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 216, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/transforms/__init__.py", line 182, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 53, in apply
    self.traverse(self.document)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 313, in traverse
    self.traverse(child)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 303, in traverse
    newnode = self.find_replace(c)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 283, in find_replace
    newnode = self.auto_toc_tree(node)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 182, in auto_toc_tree
    return self.state_machine.run_directive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/states.py", line 93, in run_directive
    direc = direc(name=name,
            ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

### Example 13:
```markdown
# Hello world

- [Google](https://www.google.com)
foo
```
Formiko output:
- [Google](https://www.google.com) foo

### Example 14:
```markdown
# Hello world

* [Google](https://www.google.com)
foo
```
Formiko output:
* [Google](https://www.google.com) foo

### Example 15:
```markdown
# Hello world

*[Google](https://www.google.com)
```

Formiko output:
*[Google](https://www.google.com)

### Example 16:
```markdown
# Hello world

-[Google](https://www.google.com)
```

Formiko output:
-[Google](https://www.google.com)

### Example 17:
```markdown
# Hello world

- [Google](https://www.google.com)
- [Google](https://www.google.com)
```
Formiko output:
```
Exception Error!

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 374, in render_output
    html = publish_string(**kwargs).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 460, in publish_string
    output, publisher = publish_programmatically(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 722, in publish_programmatically
    output = publisher.publish(enable_exit_status=enable_exit_status)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 236, in publish
    self.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 216, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/transforms/__init__.py", line 182, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 53, in apply
    self.traverse(self.document)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 313, in traverse
    self.traverse(child)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 303, in traverse
    newnode = self.find_replace(c)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 283, in find_replace
    newnode = self.auto_toc_tree(node)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 182, in auto_toc_tree
    return self.state_machine.run_directive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/states.py", line 93, in run_directive
    direc = direc(name=name,
            ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

### Example 18:
```markdown
# Hello world

* [Google](https://www.google.com)
* [Google](https://www.google.com)
```
Formiko output:
```
Exception Error!

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 374, in render_output
    html = publish_string(**kwargs).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 460, in publish_string
    output, publisher = publish_programmatically(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 722, in publish_programmatically
    output = publisher.publish(enable_exit_status=enable_exit_status)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 236, in publish
    self.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 216, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/transforms/__init__.py", line 182, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 53, in apply
    self.traverse(self.document)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 313, in traverse
    self.traverse(child)
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 303, in traverse
    newnode = self.find_replace(c)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 283, in find_replace
    newnode = self.auto_toc_tree(node)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/transform.py", line 182, in auto_toc_tree
    return self.state_machine.run_directive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/recommonmark/states.py", line 93, in run_directive
    direc = direc(name=name,
            ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```
