### ISSUE TITLE
A link referencing another document makes the preview crash

### ISSUE THREAD

**Issue by mbideau** [ondratu/formiko#35]
Try this mardown content example :
```md
# test file
A link referencing another document in the same folder is crashing, example :
[crashing link](otherdoc.md)
```
That produce the following error in the preview pane :
```text
Exception Error!

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/formiko/renderer.py", line 267, in render_output
    html = publish_string(**kwargs).decode('utf-8')
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 407, in publish_string
    output, pub = publish_programmatically(
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 665, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 220, in publish
    output = self.writer.write(self.document, self.destination)
  File "/usr/lib/python3/dist-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3/dist-packages/docutils/writers/_html_base.py", line 78, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 2018, in unknown_visit
    raise NotImplementedError(
NotImplementedError:  visiting unknown node type: pending_xref
```

If I preprend the link href with an "http://" or a "#" the exception disappear.

I think this is very problematic to not be able to use reference to other document in the same folder/tree.

PS: thank you very much for this software that is working really fine for me except for this bug :pray:

**Comment by ondratu** [comment]
Hi can you tell me which version of Formiko and which vesion of docutils you have?
```sh
pip3 list | grep -E 'formiko|docutils'
```

**Comment by mbideau** [comment]
Sure, sorry I didn't include this information from the start.

**Formiko** is from the _debian_ package of _bullseye_: **1.3.0-2** ([package web page](https://packages.debian.org/en/bullseye/amd64/formiko))
And same for the Python 3 **docutils** (package is named _python3-docutils_): **0.16+dfsg-4** ([package web page](https://packages.debian.org/en/bullseye/python3-docutils))

I also tried with formiko install from _pip3_ : **1.4.3**
And it yield almost the same error
```
Library Error

Sorry about that. This seems to be not supported functionality in dependent library Reader or Writer

Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.7/site-packages/formiko/renderer.py", line 371, in render_output
    html = publish_string(**kwargs).decode('utf-8')
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 416, in publish_string
    enable_exit_status=enable_exit_status)
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 664, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/usr/lib/python3/dist-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3/dist-packages/docutils/writers/_html_base.py", line 71, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 4 more times]
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 1907, in unknown_visit
    % (self.__class__, node.__class__.__name__))
NotImplementedError:  visiting unknown node type: pending_xref
```

Other parameters :
* Horizontal preview
* Auto scroll
* Common mark parser
* Docutils HTML 4 writer

The error seems to happen also with empty URL.

Thanks in advance for digging into it :pray:
