### ISSUE TITLE
Math module

### ISSUE THREAD

**Issue by SanPen** [ondratu/formiko#6]
Hi, 

I'm using formiko (downloaded it today) and apparently it does not compile math formulas:

```
Power, current and voltage vectors
""""""""""""""""""""""""""""""""""
.. math::
	[demand\_power ]= [C_{load,bus}]^\top \cdot [load\_power\_S]
```
The error that appears in the preview panel is this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/formiko/renderer.py", line 267, in render_output
    html = publish_string(**kwargs).decode('utf-8')
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 416, in publish_string
    enable_exit_status=enable_exit_status)
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 664, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/usr/lib/python3/dist-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/local/lib/python3.6/dist-packages/docutils_html5/__init__.py", line 106, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 1 more time]
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/local/lib/python3.6/dist-packages/docutils_html5/__init__.py", line 564, in unknown_visit
    simple_element = self.simple_elements[node.__class__.__name__]
KeyError: 'math_block'
```

**Comment by ondratu** [comment]
I See all OK. Probably problem could be somewhere on your docutils install. Which OS are you use, which python packages versions are you use?

[math.pdf](https://github.com/ondratu/formiko/files/2904091/math.pdf)

**Comment by SanPen** [comment]
Hi, I am on Ubuntu 18.04, and Formiko version is 1.3
Do you need other packages' version?

**Comment by ondratu** [comment]
Hi, i found the problem, which is in other Docutils writers. As i test, only HTML4, S5/HTML and Yet another HTML writer (https://github.com/masayuko/docutils-htmlwriter). Other Tiny HTML Writer and HTML 5 Writer does not support math block.

**Comment by ondratu** [comment]
One of possible library problem could not be solved nicely on Formiko application. So I closed this issue.
